name: 'my_first_project'
version: '1.0.0'

profile: 'my_first_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# configure all models in the example/ directory as views
models:
  my_first_project:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
    marts:
      +materialized: table
